### ISSUE TITLE
可以根据文章分类来做多个feed么？  还是说文章路径path？

### ISSUE THREAD

**Issue by appotry** [bestony/hexo-generator-podcasts#13]
可否配置成，生成多个feed,，每个feed包含一个或者多个分类categories的文章？

这样就可以让其他人只订阅感兴趣的分类文章了， 例如最新新闻，电影，音乐等等

非常想要这个功能

**Comment by ShungJhon** [comment]
请问如何生成rss feed

**Comment by appotry** [comment]
找到了另一个插件，可以满足要求 hexo-feed
